"""add cover_image_url avatar_url and user update

Revision ID: 7a0dff981951
Revises: deb1d32144fe
Create Date: 2026-03-27 16:25:23.168445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a0dff981951'
down_revision: Union[str, Sequence[str], None] = 'deb1d32144fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('curricula', sa.Column('cover_image_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('curricula', 'cover_image_url')
    # ### end Alembic commands ###
